sudo: required
services:
    - docker
    
before_install:
    - docker build -t yayayaka/docker-react -f Dockerfile.dev .
    
script:
    - docker run yayayaka/docker-react npm run test -- --coverage